### 행렬의 정렬

1. np.sort() : 넘파이에서 sort() 호출

2. np.array.sort() : 행렬자체에서 sort() 호출


####  두 방식 sort() 함수의 차이점


1. np.sort() : 원 행렬을 그대로 유지한채 원 행렬의 정렬된 행렬을 반환

2. np.array.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 None을 반환

In [11]:
import numpy as np

origin = np.array([3,1,9,7])
print('원본:', origin)

원본: [3 1 9 7]


In [12]:
# 넘파이 sort
result = np.sort(origin)
print('원본:', origin)
print('결과:',result)

원본: [3 1 9 7]
결과: [1 3 7 9]


In [15]:
# 행렬의 sort
result = origin.sort()
print('원본:', origin)
print('결과:',result)

원본: [1 3 7 9]
결과: None


### 내림차순 정렬 [::-1]

In [18]:
origin = np.array([3,1,9,7])
# 넘파이 sort - 내림차순
result = np.sort(origin)[::-1]
print(result)

[9 7 3 1]


In [21]:
# 행렬의 sort - 내림차순
# result = origin.sort()[::-1] # 에러
# result = origin.sort()
print(origin[::-1])

[9 7 3 1]


### 2차원 이상의 행렬에서 np.sort()

- axis=0 : 행방향 -> 열단위
- axis=1 : 열방향 -> 행단위

In [23]:
arr = np.array([[9, 6, 3],
                [5, 11, 2]])
arr_sort = np.sort(arr, axis=0)
print(arr_sort)
arr_sort = np.sort(arr, axis=1)
print(arr_sort)


[[ 5  6  2]
 [ 9 11  3]]
[[ 3  6  9]
 [ 2  5 11]]


In [5]:
?np.sort

####  정렬된 행렬의 인덱스 반환 : argsort()

In [25]:
arr = np.array([3, 8, 2, 5])
arr
np.argsort(arr)

array([2, 0, 3, 1], dtype=int64)

In [27]:
score = np.array([66,99,55,88,77])
names = np.array(['홍','김','박','최','이'])

idx = np.argsort(score)

for i in idx:
    print(names[i],'-', score[i])

박 - 55
홍 - 66
이 - 77
최 - 88
김 - 99
